name: CI

on:
  push:
    branches:
      - main
      - "feat/**"
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  terraform-checks:
    name: Terraform + Checkov
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          quiet: true
          soft_fail: false